apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nps-backend
  name: nps-backend
spec:
  ports:
  - name: "1940"
    port: 1940
    targetPort: 1940
  selector:
    io.kompose.service: nps-backend
  type: NodePort
status:
  loadBalancer: {}
